routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['prefix'=>'admin','middleware'=>'admin'],function(){

Route::resource('ziyaretci','ZiyaretController');

Route::resource('kart','KartController');

Route::get('/cikis-yaptir/{id}','ZiyaretController@cikis_yaptir')->name('ziyaretci.cikis');

Route::get('/ziyaretciler-dun', 'ZiyaretController@ziyaretci_dun')->name('ziyaretci.dun');

Route::get('/ziyaretciler-hafta', 'ZiyaretController@ziyaretci_hafta')->name('ziyaretci.hafta');

Route::get('/ziyaretciler-ay', 'ZiyaretController@ziyaretci_ay')->name('ziyaretci.ay');

Route::get('/ziyaretciler-tum', 'ZiyaretController@ziyaretci_tum')->name('ziyaretci.tum');

Route::get('birim-getir','ZiyaretController@birim_getir')->name('birim.getir');

});


Route::get('/kullanici-ekle', 'KullaniciController@kullaniciekle')->name('kullanici.ekle');

Route::post('/kullanicikayit','KullaniciController@kullanicikayit')->name('kullanici.kayit');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

resources/views/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Profil</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    Başarıyla giriş yaptınız.
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kart-duzenle.blade.php
@extends('layouts.layout')

@section('title')
    Kart Düzenleme Sayfası
@endsection

@section('content')
   
<div class="content-wrapper">
    <section class="content-header">
      <h1>
        Kart Düzenleme
      </h1>    
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">

            @include('errors')

          <div class="box box-primary">            
            {{-- <form action="{{ route('kart.update',$kart->id) }}" method="PUT"> --}}
                {{-- {!! Form::model($kart,['route' => ['kart.update',$kart->id], 'method' => 'PUT']) !!} --}}
                <form action="{{ route('kart.update',$kart->id) }}" method="POST">
                  @csrf
                  @method('PUT')
                <div class="box-body">

                    <div class="form-group">
                    <label for="exampleInputEmail1">Kart Adı</label>
                    <input type="text" name="kart_ad" class="form-control" id="exampleInputEmail1" value="{{$kart->kart_adi}}" placeholder="Kart adı giriniz..">
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Güncelle</button>
                </div>
                {{-- {!! Form::close() !!} --}}
            </form>
          </div>
        </div>       
      </div>
    </section>
  </div>

@endsection

resources/views/kart-ekle.blade.php
@extends('layouts.layout')

@section('title')
    Kart Ekleme Sayfası
@endsection

@section('content')
   
<div class="content-wrapper">
    <section class="content-header">
      <h1>
        Kart Ekle
      </h1>    
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">

            @include('errors')

          <div class="box box-primary">            
            <form action="{{ route('kart.store') }}" method="POST">
              @csrf

            <div class="box-body">
                <div class="form-group">
                  <label for="exampleInputEmail1">Kart Adı</label>
                  <input type="text" name="kart_ad" class="form-control" id="exampleInputEmail1" placeholder="Kart adı giriniz..">
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">Ekle</button>
            </div>

              </form>
          </div>
        </div>       
      </div>
    </section>
  </div>

@endsection

resources/views/kartlar.blade.php
@extends('layouts.layout')

@section('title')
    Kartlar Sayfası
@endsection

@section('content')

<div style="float:right; margin:15px 15px 22px 0;"><a  href="{{route('kart.create')}}" class="btn btn-success">Kart Ekle</a></div>

<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Kartlar
          </h1>
        </section>
        <!-- Main content -->
        
        <section class="content">
          
          <!-- /.row -->
          <div class="row">
            <div class="col-xs-12">
             @if(count($kartlar) > 0)
              <div class="box">
                <div class="box-header">
                  <div class="box-tools">
                   
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <thead>
                        <tr>
                            <th width="50%">Kart Adı</th>
                            <th width="5%">Düzenle</th>
                          </tr>
                        </thead>
                    <tbody>

                      @foreach ($kartlar as $kart)
                      <tr>
                          <td>{{$kart->kart_adi}}</td>
                          <td>
                            <a class="btn btn-primary" href="{{route('kart.edit',$kart->id)}}">Düzenle</a>
                         </td>
                         {{-- <td>
                            {!! Form::model($kart,['route' => ['kart.destroy',$kart->id],'method' => 'DELETE']) !!}
                                <button type="submit" value="Sil" class="btn btn-danger" onclick="javascript:return confirm('Silinsin mi?');">Sil</button>
                            {!! Form::close() !!}                         
                        </td> --}}
                      </tr>
                      @endforeach
                      
                    </tbody>
                  </table>
                  {{ $kartlar->links() }}
                </div>
                <!-- /.box-body -->
              </div>
              @else
              <br>
                <div class="alert alert-warning">Kayıt bulunamadı.</div>
              @endif
      
              <!-- /.box -->
            </div>
          </div>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
    

@endsection

resources/views/ziyaretci-duzenle.blade.php
@extends('layouts.layout')

@section('title')
    Ziyaretçi Düzenleme Sayfası
@endsection

@section('content')
   
<div class="content-wrapper">
    <section class="content-header">
      <h1>
        Ziyaretçi Düzenleme
      </h1>    
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">

            @include('errors')

          <div class="box box-primary">            
            {{-- <form action="{{ route('ziyaretci.update',$ziyaretci->id) }}" method="PUT"> --}}
              {{-- {!! Form::model($ziyaretci,['route' => ['ziyaretci.update',$ziyaretci->id], 'method' => 'PUT']) !!} --}}
              <form action="{{ route('ziyaretci.update',$ziyaretci->id) }}" method="POST">

                @csrf
                @method('PUT')

            <div class="box-body">

                <div class="form-group">
                  <label for="exampleInputEmail1">Ziyaretçi Ad</label>
                  <input type="text" name="ad" class="form-control" id="exampleInputEmail1" value="{{$ziyaretci->ad}}" placeholder="Ad giriniz..">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaretçi Soyad</label>
                  <input type="text" name="soyad" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->soyad}}" placeholder="Soyad giriniz..">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Ziyaretçi Kimlik Belgesi Türü</label>
                    <input type="text" name="belge" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->belge}}" placeholder="Kimlik belge türü giriniz.">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaretçi Kimlik Numarası</label>
                  <input type="text" name="kimlik_no" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->tc_kimlik}}" placeholder="Belge Numarasını boşluk bırakmadan giriniz.">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaretçi Telefon</label>
                  <input type="text" name="telefon" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->telefon}}" placeholder="Telefon Numarasını boşluk bırakmadan giriniz.">
                </div>

                <div class="form-group">
                  <label for="kurum">Ziyaret Edilen Birim</label>
                  <select id="kurum" name="kurum" class="form-control">
                    @foreach ($kurumlar as $kurum)
                      <option value="{{ $kurum->id }}" {{$kurum->id == old('kurum_id',$ziyaretci->kurum_id) ? 'selected' : '' }}>{{ $kurum->kurum_adi }}</option>             
                    @endforeach
                  </select>
                </div>

                <div class="form-group">
                    <label for="birim">Ziyaret Edilen Müdürlük</label>
                    <select id="birim" name="birim" class="form-control">
                      <option value="">Müdürlük Seçiniz</option>
                        @foreach ($alt_birimler as $alt_birim)
                          <option value="{{ $alt_birim->id }}" {{$alt_birim->id == old('birim_id',$ziyaretci->birim_id) ? 'selected' : '' }}>{{ $alt_birim->kurum_adi }}</option>                 
                         @endforeach 
                    </select>
                </div>
                @if ($ziyaretci->seflik_id)
                  <div class="form-group">
                    <label for="seflik">Ziyaret Edilen Şeflik</label>
                    <select id="seflik" name="seflik" class="form-control">
                        @foreach ($seflikler as $seflik)
                          <option value="{{ $seflik->id }}" {{$seflik->id == old('seflik_id',$ziyaretci->seflik_id) ? 'selected' : '' }}>{{ $seflik->kurum_adi }}</option>                 
                        @endforeach 
                    </select>
                  </div>
                @else
                  <div id="sef_div" style="display:none;" class="form-group">
                    <label for="seflik">Ziyaret Edilen Şeflik</label>
                    <select id="seflik" name="seflik" class="form-control">
                        <option value="">Şeflik Seçiniz</option>             
                    </select>
                  </div>
                @endif

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaret Edilen Kişi</label>
                  <input type="text" name="ziyaret_edilen" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->ziyaret_edilen}}" placeholder="Ziyaret edilecek kişiyi giriniz..">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaret Sebebi</label>
                  <input type="text" name="ziyaret_sebebi" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->ziyaret_sebebi}}" placeholder="Ziyaret sebebi giriniz..">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Ziyaretçi Firma Adı</label>
                    <input type="text" name="firma" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->firma}}" placeholder="Ziyaretçinin firma adını giriniz giriniz (Zorunlu Değil).">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Ziyaretçi Araç Plakası</label>
                    <input type="text" name="plaka" class="form-control" id="exampleInputPassword1" value="{{$ziyaretci->arac_plaka}}" placeholder="Ziyaretçinin araç plakasını giriniz (Zorunlu Değil).">
                </div>
              
                <div class="form-group">
                  <label for="kart">Kart Numarası</label>
                  <select id="kart" name="kart-no" class="form-control">
                      <option value="0">Kart seçiniz.</option>
                    @foreach ($kartlar as $kart)
                      <option value="{{ $kart->id }}" {{$kart->id == old('kart_no',$ziyaretci->kart_no) ? 'selected' : '' }}>{{ $kart->kart_adi }}</option>
                    @endforeach
                  </select>
                </div>

            </div>

                <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Güncelle</button>
                </div>
              </form>
              {{-- {!! Form::close() !!} --}}
          </div>
        </div>       
      </div>
    </section>
  </div>

  <script type="text/javascript">

    $('#kurum').on('change',function(){
        var kurum = $(this).val();    
        $("#birim").empty();
        $("#birim").append('<option value="">Birim Seçiniz</option>');
        if(kurum){
            $.ajax({
               type:"GET",
               url:"{{url('admin/birim-getir')}}?kurum_id="+kurum,
               success:function(res){               
                if(res){
                    $.each(res,function(key,value){
                        $("#birim").append('<option value="'+key+'">'+value+'</option>');
                    });
               
                }else{
                   $("#birim").empty();
                }
               }
            });
        }else{
            $("#birim").empty();
        }
            
       });


       $('#birim').on('change',function(){

        var birim = $(this).val();

        $("#seflik").empty();
        $("#seflik").append('<option value="">Şeflik Seçiniz</option>');

        if( birim == 52 || birim == 53 || birim == 54 || birim == 55 || birim == 56 || birim == 57 || birim == 58)
        {
          $('#sef_div').removeAttr('style');

          $.ajax({
            type:"GET",
            url:"{{url('admin/birim-getir')}}?kurum_id="+birim,
            success:function(res){               
              if(res){
                  $.each(res,function(key,value){
                      $("#seflik").append('<option value="'+key+'">'+value+'</option>');
                  });
            
              }else{
                $("#seflik").empty();
              }
            }
          });
        }
        else
        {
          $('#sef_div').css('display','none'); 
        }
        }
        );
    
    
    </script>
    


@endsection

resources/views/ziyaretci-ekle.blade.php
@extends('layouts.layout')

@section('title')
    Ziyaretçi Ekleme Sayfası
@endsection

@section('content')
   
<div class="content-wrapper">
    <section class="content-header">
      <h1>
        Ziyaretçi Giriş Ekle
      </h1>    
    </section>

    <section class="content">
      <div class="row">
        <div class="col-md-12">

            @include('errors')

          <div class="box box-primary">            
            <form action="{{ route('ziyaretci.store') }}" method="POST">
              @csrf
            <div class="box-body">

                <div class="form-group">
                  <label for="exampleInputEmail1">Ziyaretçi Ad</label>
                  <input type="text" name="ad" class="form-control" id="exampleInputEmail1" placeholder="Ad giriniz..">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaretçi Soyad</label>
                  <input type="text" name="soyad" class="form-control" id="exampleInputPassword1" placeholder="Soyad giriniz..">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Ziyaretçi Kimlik Belgesi Türü</label>
                    <input type="text" name="belge" class="form-control" id="exampleInputPassword1" placeholder="Kimlik belge türü giriniz.">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaretçi Kimlik Numarası</label>
                  <input type="text" name="kimlik_no" class="form-control" id="exampleInputPassword1" placeholder="Belge Numarasını boşluk bırakmadan giriniz.">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaretçi Telefon</label>
                  <input type="text" name="telefon" class="form-control" id="exampleInputPassword1" placeholder="Telefon Numarasını boşluk bırakmadan giriniz.">
                </div>

                <div class="form-group">
                  <label for="kurum">Ziyaret Edilen Birim</label>
                  <select id="kurum" name="kurum" class="form-control">
                    @foreach ($kurumlar as $kurum)
                      <option value="{{ $kurum->id }}">{{ $kurum->kurum_adi }}</option>             
                    @endforeach
                  </select>
                </div>

                <div class="form-group">
                  <label for="birim">Ziyaret Edilen Müdürlük</label>
                  <select id="birim" name="birim" class="form-control">
                      <option value="">Birim Seçiniz</option>             
                  </select>
                </div>

                <div id="sef_div" style="display:none;" class="form-group">
                  <label for="seflik">Ziyaret Edilen Şeflik</label>
                  <select id="seflik" name="seflik" class="form-control">
                      <option value="">Şeflik Seçiniz</option>             
                  </select>
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaret Edilen Kişi</label>
                  <input type="text" name="ziyaret_edilen" class="form-control" id="exampleInputPassword1" placeholder="Ziyaret edilecek kişiyi giriniz..">
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Ziyaret Sebebi</label>
                  <input type="text" name="ziyaret_sebebi" class="form-control" id="exampleInputPassword1" placeholder="Ziyaret sebebi giriniz..">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Ziyaretçi Firma Adı</label>
                    <input type="text" name="firma" class="form-control" id="exampleInputPassword1" placeholder="Ziyaretçinin firma adını giriniz giriniz (Zorunlu Değil).">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1">Ziyaretçi Araç Plakası</label>
                    <input type="text" name="plaka" class="form-control" id="exampleInputPassword1" placeholder="Ziyaretçinin araç plakasını giriniz (Zorunlu Değil).">
                </div>
              
                <div class="form-group">
                  <label for="kart">Kart</label>
                  <select id="kart" name="kart-adi" class="form-control">
                    <option value="0">Kart seçiniz.</option>
                    @foreach ($kartlar as $kart)
                      <option value="{{ $kart->id }}">{{ $kart->kart_adi }}</option>             
                    @endforeach
                  </select>
                </div>

            </div>

                <div class="box-footer">
                  <button type="submit" class="btn btn-primary">Ekle</button>
                </div>
              </form>
          </div>
        </div>       
      </div>
    </section>
  </div>

<script type="text/javascript">

$('#kurum').on('change',function(){
    var kurum = $(this).val();    
    $("#birim").empty();
    $("#birim").append('<option value="">Birim Seçiniz</option>');
    if(kurum){
        $.ajax({
           type:"GET",
           url:"{{url('admin/birim-getir')}}?kurum_id="+kurum,
           success:function(res){               
            if(res){
                $.each(res,function(key,value){
                    $("#birim").append('<option value="'+key+'">'+value+'</option>');
                });
           
            }else{
               $("#birim").empty();
            }
           }
        });
    }else{
        $("#birim").empty();
    }
        
   });



   $('#birim').on('change',function(){

      var birim = $(this).val();
      
      $("#seflik").empty();
      $("#seflik").append('<option value="">Şeflik Seçiniz</option>');

      if( birim == 52 || birim == 53 || birim == 54 || birim == 55 || birim == 56 || birim == 57 || birim == 58)
      {
        $('#sef_div').removeAttr('style');

        $.ajax({
           type:"GET",
           url:"{{url('admin/birim-getir')}}?kurum_id="+birim,
           success:function(res){               
            if(res){
                $.each(res,function(key,value){
                    $("#seflik").append('<option value="'+key+'">'+value+'</option>');
                });
           
            }else{
               $("#seflik").empty();
            }
           }
        });
      }
      else
      {
         $('#sef_div').css('display','none'); 
      }
    }
   );


</script>

@endsection

resources/views/ziyaretciler-ay.blade.php
@extends('layouts.layout')

@section('title')
    Bu Ay Gelen Ziyaretçiler
@endsection

@section('content')

<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Aylık Ziyaretçiler
          </h1>
        </section>
        <!-- Main content -->
        <section class="content">
          
          <!-- /.row -->
          <div class="row">
            <div class="col-xs-12">
             @if(count($ziyaretciler) > 0)
              <div class="box">
                <div class="box-header">
                  <div class="box-tools">
                   
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>AD</th>
                        <th>SOYAD</th>
                        {{-- <th>TC Kimlik No</th> --}}
                        <th>Telefon Numarası</th>
                        <th>Tarih</th>
                        <th>Giriş Saati</th>
                        <th>Çıkış Saati</th>
                        <th>Ziyaret Edilen Kişi</th>
                        <th>Ziyaret Sebebi</th>
                        {{-- <th>Durum</th> --}}
                        <th>Çıkış Yap</th>
                        <th>Detay</th>
                      </tr>
                    </thead>
                    <tbody>

                      @foreach ($ziyaretciler as $ziyaretci)
                      <tr>
                          <td>{{$ziyaretci->ad}}</td>
                          <td>{{$ziyaretci->soyad}}</td>
                          {{-- <td>{{$ziyaretci->tc_kimlik}}</td> --}}
                          <td>{{$ziyaretci->telefon}}</td>
                          <td>{{ Carbon\Carbon::parse($ziyaretci->ziyaret_tarihi)->format('d-m-Y') }}</td>
                          <td>{{$ziyaretci->giris_saati}}</td>
                          <td>
                              {{$ziyaretci->cikis_saati}}
                          </td>
                          <td>{{$ziyaretci->ziyaret_edilen}}</td>
                          <td>{{$ziyaretci->ziyaret_sebebi}}</td>
                          {{-- <td>
                              @if (!empty($ziyaretci->cikis_saati))
                                <span class="btn btn-success">Çıkış Yaptı</span>
                              @else 
                                <span class="btn btn-warning">İçerde</span>
                              @endif
                          </td> --}}
                          <td>
                              @if (empty($ziyaretci->cikis_saati))
                                <a class="btn btn-success" href="{{ route('ziyaretci.cikis', $ziyaretci->id) }}">Çıkış</a>
                              @else 
                                <span class="btn btn-danger">Çıkış Yaptı</span>
                              @endif
                          </td>
                          <td>
                            <a class="btn btn-primary" href="{{route('ziyaretci.show',$ziyaretci->id)}}">Detay</a>
                          </td>
                      </tr>
                      @endforeach
                      
                    </tbody>
                  </table>
                  {{ $ziyaretciler->links() }}
                </div>
                <!-- /.box-body -->
              </div>
              <!-- /.box -->
              @else
              <br>
                <div class="alert alert-warning">Kayıt bulunamadı.</div>
              @endif      
            </div>
          </div>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
    

@endsection

resources/views/ziyaretciler-bugun.blade.php
@extends('layouts.layout')

@section('title')
    Bugünkü Ziyaretçiler
@endsection

@section('content')

<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Bugünkü Ziyaretçiler
          </h1>
        </section>
        <!-- Main content -->
        
        <section class="content">
          
          <!-- /.row -->
          <div class="row">
            <div class="col-xs-12">
             @if(count($ziyaretciler) > 0)
              <div class="box">
                <div class="box-header">
                  <div class="box-tools">
                   
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>AD</th>
                            <th>SOYAD</th>
                            {{-- <th>TC Kimlik No</th> --}}
                            <th>Telefon Numarası</th>
                            <th>Tarih</th>
                            <th>Giriş Saati</th>
                            <th>Çıkış Saati</th>
                            <th>Ziyaret Edilen Kişi</th>
                            <th>Ziyaret Sebebi</th>
                            {{-- <th>Durum</th> --}}
                            <th>Çıkış Yap</th>
                            <th>Detay</th>
                            <th>Düzenle</th>
                          </tr>
                        </thead>
                    <tbody>

                      @foreach ($ziyaretciler as $ziyaretci)
                      <tr>
                          <td>{{$ziyaretci->ad}}</td>
                          <td>{{$ziyaretci->soyad}}</td>
                          {{-- <td>{{$ziyaretci->tc_kimlik}}</td> --}}
                          <td>{{$ziyaretci->telefon}}</td>
                          <td>{{ Carbon\Carbon::parse($ziyaretci->ziyaret_tarihi)->format('d-m-Y') }}</td>
                          <td>{{$ziyaretci->giris_saati}}</td>
                          <td>
                              {{$ziyaretci->cikis_saati}}
                          </td>
                          <td>{{$ziyaretci->ziyaret_edilen}}</td>
                          <td>{{$ziyaretci->ziyaret_sebebi}}</td>
                          {{-- <td>
                              @if (!empty($ziyaretci->cikis_saati))
                                <span class="btn btn-success">Çıkış Yaptı</span>
                              @else 
                                <span class="btn btn-warning">İçerde</span>
                              @endif
                          </td> --}}
                          <td>
                              @if (empty($ziyaretci->cikis_saati))
                                <a class="btn btn-success" href="{{ route('ziyaretci.cikis', $ziyaretci->id) }}">Çıkış</a>
                              @else 
                                <span class="btn btn-danger">Çıkış Yaptı</span>
                              @endif
                          </td>
                          <td>
                              <a class="btn btn-primary" href="{{route('ziyaretci.show',$ziyaretci->id)}}">Detay</a>
                          </td>
                          <td>
                              <a class="btn btn-success" href="{{route('ziyaretci.edit',$ziyaretci->id)}}">Düzenle</a>
                          </td>
                      </tr>
                      @endforeach
                      
                    </tbody>
                  </table>
                  {{ $ziyaretciler->links() }}
                </div>
                <!-- /.box-body -->
              </div>
              @else
              <br>
                <div class="alert alert-warning">Kayıt bulunamadı.</div>
              @endif
      
              <!-- /.box -->
            </div>
          </div>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
    

@endsection